baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-air'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
unsafe = true  # Ensure this is placed in the [Params] section

[languages.en.menu]
  [[languages.en.menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 20

  [[languages.en.menu.main]]
    name = "Features"
    pageRef = "/features"
    weight = 30

  [[languages.en.menu.main]]
    name = "Gallery Masonry"
    pageRef = "/en/gallery-masonry/"
    weight = 60

  [[languages.en.menu.main]]
    name = "Collision Repair"
    pageRef = "/en/rv-services/collision-motorhome-repair/"
    weight = 65

  [[languages.en.menu.main]]
    name = "Slider"
    pageRef = "/rv/slider/"
    weight = 65

  [[languages.en.menu.main]]
      name = "Custom Slider"
      pageRef = "/rv/custom-slider/"
      weight = 70

  [[languages.en.menu.main]]
      name = "Swiper Page"
      url = "/swiper-page/"
      weight = 50
